{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auramed-edge-ingress
  labels:
    app.kubernetes.io/name: auramed-ingress
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    # Enforces Modern TLS 1.3 and TLS 1.2 Strict Cipher Suites
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS13-1-2-2021-06"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.global.certificateArn | quote }}
    # AWS ALB Mutual Authentication (mTLS) with Client TrustStore
    alb.ingress.kubernetes.io/mutual-authentication: {{ .Values.ingress.annotations.mutualAuthentication | default "{\"mode\":\"verify\",\"trustStoreArn\":\"arn:aws:elasticloadbalancing:us-east-1:123456789012:truststore/auramed-mtls-clients/a1b2c3d4\"}" | quote }}
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          # 1. Edge Ingestion Gateway (FHIR R4 & Claims)
          - path: /api/v1/fhir
            pathType: Prefix
            backend:
              service:
                name: auramed-ingestion-gateway
                port:
                  number: 8080
          - path: /api/v1/claims
            pathType: Prefix
            backend:
              service:
                name: auramed-ingestion-gateway
                port:
                  number: 8080
          # 2. HL7 CDS Hooks Discovery & Hook Execution
          - path: /cds-services
            pathType: Prefix
            backend:
              service:
                name: auramed-cds-hooks
                port:
                  number: 8080
{{- end }}
