apiVersion: v1
kind: Service
metadata:
  name: auramed-ingestion-gateway
  labels:
    app.kubernetes.io/name: auramed-ingestion-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: auramed-ingestion-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: auramed-flink-jobmanager
  labels:
    app.kubernetes.io/name: auramed-flink-jobmanager
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      name: web
    - port: 6123
      targetPort: 6123
      name: rpc
  selector:
    app.kubernetes.io/name: auramed-flink-jobmanager
---
apiVersion: v1
kind: Service
metadata:
  name: auramed-triton-server
  labels:
    app.kubernetes.io/name: auramed-triton-server
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      name: http
    - port: 8001
      targetPort: 8001
      name: grpc
  selector:
    app.kubernetes.io/name: auramed-triton-server
---
apiVersion: v1
kind: Service
metadata:
  name: auramed-cds-hooks
  labels:
    app.kubernetes.io/name: auramed-cds-hooks
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app.kubernetes.io/name: auramed-cds-hooks
